### ISSUE TITLE
Minknow installed with errors

### ISSUE THREAD

**Issue by MirzaSamnani** [sirselim/jetson_nanopore_sequencing#1]
Hey there, I followed exact steps of your setup, just that we dont have an SSd yet but rest all as it is on a AGX. While installing there were these errors- 

Error were encountered while processing:
minknow-core-minit-offline
ont-bream4-minit
ont-configuration-customer-minit

The software does still open  but does not detect any of the minion devices.

On a Ubuntu running on a laptop it installed simply using sudo apt-get install minion-nc and all devices show up fine there.

What do you suggest for resolving those errors?

**Comment by sirselim** [comment]
Hi @MirzaSamnani - my first guess would be that you might be pointing at the wrong repository. The packages you listed are all MinIT packages, so you should be using the MinIT repository:

`deb [trusted=yes] http://mirror.oxfordnanoportal.com/apt xenial-stable-minit non-free`

If you use any other repository those packages 'don't exist', so won't be installed. 

You find the setup instructions include this step if you want to double check. 

Hopefully this is the solution. 🙂

**Comment by sirselim** [comment]
This turned out to be an issue of incorrect user accounts and permissions. Marking as solved.
