### ISSUE TITLE
MinION not recognised with mk1c setup on Xavier AGX

### ISSUE THREAD

**Issue by PhiloVa** [sirselim/jetson_nanopore_sequencing#17]
Hi,
Although I had the minit installation up and working on the Xavier (with some glitches), the mk1c setup (with latest guppy) seems not to recognize the USB connection of the MinION. I tried both purging the old installation and reflashing the Xavier with same result.
The condition seems similar to the issues existing in the community discussion on Oct 2020 for the original minit preparation (https://gist.github.com/sirselim/2ebe2807112fae93809aa18f096dbb94#gistcomment-3483410). 
The Minknow status is active but the MinION is fanning like crazy. I tried changing permission to the usb device with no luck.
For now I have reverted to the older minit installation which works for now, but I thought it would be good to mention it here.

**Comment by sirselim** [comment]
Closing this issue as its been a few months now. The Mk1c repository is working reliably on multiple ARM based boards.

Please feel free to reopen if you're still having trouble.
