### ISSUE TITLE
Add specific instructions to include guppyd.service 

### ISSUE THREAD

**Issue by sirselim** [sirselim/jetson_nanopore_sequencing#18]
It was brought to my attention by @mikblack this afternoon that on his Xavier AGX build MinKNOW and Guppy weren't "talking" to each other. This was running the latest builds as of 2021-11-30, MinKNOW 21.10.8 (Mk1c version) and Guppy 5.0.17.

My suggestion was to try adding `guppyd.service` to the set up (I've been doing this by default since seeing it introduced). Turns out this fixed the issue. So this is a reminder to myself to include the `guppyd.service` in the same step as `minknow.service`, which should prevent this problem in the future.

**Comment by sirselim** [comment]
I have pushed an update that includes the instructions to copy across `guppyd.service` to the correct location and start the service.

I will leave this issue open until I have had a chance to write a little more about potential modifications to the `guppyd.service` in terms of tweaks to RAM limits etc for specific GPUs/devices.

**Comment by starnoux** [comment]
Dear @sirselim,

We had the gpu running but had to upgrade some of the software. And while re-installing the gpu connection. I encounter a weird error.
I made the guppyd.service as you propose. And when trying to enable it, the following error pop up:
```
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
```
Would you have any idea why it does not recognise the [Install] ?
I followed up, not installing minion-nc but the 5 packages adviced and in a next step the ont-guppy.
```
minion-nc:
  Installé : (aucun)
  Candidat : 22.08.8-1~focal
 Table de version :
     22.08.8-1~focal 10
         10 http://mirror.oxfordnanoportal.com/apt focal-stable/non-free amd64 Packages
         10 http://mirror.oxfordnanoportal.com/apt focal-stable/non-free i386 Packages
(base) remi_bernard@CW19054876:~$ apt policy ont-guppy
ont-guppy:
  Installé : 6.3.7-1~focal
  Candidat : 6.3.7-1~focal
 Table de version :
 *** 6.3.7-1~focal 100
         10 http://mirror.oxfordnanoportal.com/apt focal-stable/non-free amd64 Packages
        100 /var/lib/dpkg/status
```

The thing I don"t understand is that the guppyd.service is loaded and active when I check.

Any idea on why the 'enabling' does not work ?

Thanks a lot for you help,
Best
Stéphanie

**Comment by sirselim** [comment]
This issue will be addressed with the major repo update that should happen in the next few days. 😄

**Comment by starnoux** [comment]
Awesome :-) We are so much looking forward to it.
