### ISSUE TITLE
h5py.zip in setup-guide.txt

### ISSUE THREAD

**Issue by mikblack** [sirselim/jetson_nanopore_sequencing#2]
On line 28 of setup-guide.txt you've got:

unzip h5py.zip

but h5py.zip is located at:

./libs/python2.7/h5py.zip
./libs/python3.7/h5py.zip

and the working directory (at this point in the script) is:

/home/minit/jetson_nanopore_sequencing

so h5py.zip won't be found.

**Comment by mikblack** [comment]
The above also causes an issue at line 99:

sudo cp -r h5py/ /opt/ont/minknow/ont-python/lib/python3.7/site-packages/

Needs to be:

sudo cp -r libs/python3.7/h5py/ /opt/ont/minknow/ont-python/lib/python3.7/site-packages/

**Comment by sirselim** [comment]
Hi @mikblack - right you are! Funny how muscle memory builds when you run through this thing 20+ times...

Thanks for catching those and I've amended the file.
