### ISSUE TITLE
update location of guppyd.service in setup-guide-mk1c.txt

### ISSUE THREAD

**Issue by devindrown** [sirselim/jetson_nanopore_sequencing#20]
With the new organization of the code, the location of the guppyd.service changed.

L165 of setup-guide-mk1c.txt

https://github.com/sirselim/jetson_nanopore_sequencing/blob/9f11430fa34340f6f9a1789dbc7eb2998cc1b0c5/setup-guide-mk1c.txt#L165

could be changed to

`sudo cp ./systemd_files/guppyd.service /lib/systemd/system/ `

**Comment by sirselim** [comment]
Thanks @devindrown good spotting! I have fixed this.
