### ISSUE TITLE
Connection/Configuration of the commend line in the minKnow interface to run guppy_basecaller

### ISSUE THREAD

**Issue by starnoux** [sirselim/jetson_nanopore_sequencing#21]
Hi Miles,

First of all, thanks a lot for your repository @sirselim, I have been following your recommendations to install and get guppy to run on the GPU. And it worked fine in command line. 

I am writing for an Issue with the MinKnow interface. 
Basically, I created guppyd.service and check the app_conf but when I open the interface it sends me back an error stating:
`/usr/bin/guppy_basecaller --port 5555 --server_file_load_timeout 600 --num_callers=1 --save_path /var/lib/minknow/data/... --input_path /var/lib/minknow/data/...--compress_fastq --recursive --barcode_kits EXP-NBD104 EXP-NBD114 --progress_stats_frequency=2`
`Unexpected option '--port' found on command line.
Unexpected option '--server_file_load_timeout' found on command line.`
And by running the command without these options, it works fine. 

I wonder if it might come from an option that I would have missed. How to modify the options that are sent from MinKnow to guppy_basecaller ?

Thanks a lot for your help,
Stéph

**Comment by sirselim** [comment]
Hi @starnoux - I think you just need to change the guppy binary from `guppy_basecaller` to `guppy_basecall_client`. Interested see if that helps.

**Comment by starnoux** [comment]
Hi @sirselim - I tried to change the binary as you mentionned, and indeed my log error has changes to: 
```
INFO: starting_up (basecall_manager)
    version: 4.4.3
    hostname: xxx
INFO: manager_notified_new_local_auth_token (util)
    expires_in: 7577852919447703365ns
    token_type: internal
INFO: manager_notified_new_local_auth_token (util)
    expires_in: 89999963933293ns
    token_type: local
INFO: running_client (basecall_manager)
    id: 1
    arguments: --port
               5555
               --server_file_load_timeout
               600
               --num_callers=1
               --save_path
               /var/lib/minknow/data/basecalling
               --config
               dna_r9.4.1_450bps_hac.cfg
               --input_path
               /var/lib/minknow/data
               --compress_fastq
               --recursive
    executable: /usr/bin/guppy_basecaller_client
WARNING: output_unexpectedly_terminated (basecall_manager)
    id: 1
    error: (2:std::asio.misc): [0x0x1c04e40]: End of file
ERROR: analysis_process_failed (basecall_manager)
    id: 1
    exit_code: 1
    output:
```
Some colleagues on the community, say that it is enough to run the command line, but I thought it would be easier for my lab colleagues. Do you think the issue is solvable ?

Thanks a lot for the response and the help so far :) highly appreciated.

**Comment by starnoux** [comment]
Hello, you can close this issue, it seems that the versions didn't work with minKnow and at the time, an upgrade had made it possible. Thanks a lot for the help.
