### ISSUE TITLE
Support for Jetson Orin?

### ISSUE THREAD

**Issue by mcrone** [sirselim/jetson_nanopore_sequencing#24]
I’ve tried to follow the setup but it doesn’t seem to work for the new Orin. I’m assuming that this is to do with the new Jetpack?

Out of interest, does the “hardware test” pass when it is working correctly in MinKNOW?

**Comment by sirselim** [comment]
Hi @mcrone - this will be because there is currently no CUDA 11 version of Guppy for ARM64 devices. Orin is running the latest CUDA from what I can see.

**Comment by mcrone** [comment]
That’s what I thought… and no current way to install cuda 10 as far as I can see…

Hoping that support will be added soon!

**Comment by sirselim** [comment]
Before I left my old job I had access to a Clara AGX unit which could switch between CUDA 10 and 11, depending on the GPU that was being used. It has the Xavier AGX (CUDA 10) as well as a RTX6000 (running on CUDA 11).

I spent a little bit of time trying to downgrade to CUDA 10 but as far as I could tell it wasn't going to be possible.
