### ISSUE TITLE
MinION mk1b cannot be detected by latest MinKNOW

### ISSUE THREAD

**Issue by tongda** [sirselim/jetson_nanopore_sequencing#26]
I followed the setup-guide-mk1c.txt to install MinKNOW on Jetson Xavier NX. However, after plug my MinION mk1c device to Jetson, nothing happened.

Refer to #17 , I tried to run `sudo /opt/ont/minknow/bin/minion_ctl init`, but the command `minion_ctl` does not exist.

Refer to #22 , I tried to run `sudo sed -i -e 's/"device_type":.*/"device_type": "MinION",/' -e 's/"host_type":.*/"host_type": "PC",/' /opt/ont/minknow/conf/app_conf`, but it seems there are not fields called "device_type" and "host_type" in `app_conf` anymore.

So I checked the version I have installed:

* MinKNOW: 22.08.9
* MinKNOW Core: 5.2.4

From the guide, the tested version combination should be MinKNOW (21.11.07) and MinKNOW Core (4.5.4). I suspect that the latest version of MinKNOW is significantly different from the older version.

Is there any workaround for the latest version of MinKNOW to detect mk1b device?

Or is there a way to install the older version of MinKNOW?

**Comment by sirselim** [comment]
Hi @tongda - the latest version of MinKNOW (and the versions for quite some time now) are based on the Ubuntu Bionic OS. This GitHub repo hasn't been updated yet for various reasons, but I can tell you that I now have a stable procedure for getting the latest MinKNOW up and running on Jetson boards. Please note that for now you'll need to be running a Jetpack from the 4.X versions, the newer 5.X Jetpacks have moved to Ubuntu Focal and CUDA 11 which at this stage isn't compatible with the versions of Guppy that are available for ARM boards.

I will give this repository a big update in the next few days. I'm always happy to hear feedback etc. on how the process is working (or not).

**Comment by sirselim** [comment]
I'm going to close this issue as I believe it fixed with the incoming updates.
