### ISSUE TITLE
Installing ONT packages

### ISSUE THREAD

**Issue by mikblack** [sirselim/jetson_nanopore_sequencing#3]
On line 64:

cat ont-package-list-xavier.txt | xargs sudo apt-get install

For me, the following package required manual interaction to specify mail delivery options:

ont-bream4-minit

Trying to install via xargs didn't allow for this to be specified (and installation of packages had to be aborted).

**Comment by sirselim** [comment]
Hi @mikblack - hmmm, so I can fix the first issue:

`cat ont-package-list-xavier.txt | xargs sudo apt-get install -y`

Adding the `-y` to say yes to all works at my end.

The second issue is interesting and I don't get that happening. I might try to put a new SD card in a Xavier NX and see if I can replicate this.

Thanks for the sleuthing.
