### ISSUE TITLE
Question about obtaining ont_pyguppy_client_lib for ARM64

### ISSUE THREAD

**Issue by hasindu2008** [sirselim/jetson_nanopore_sequencing#4]
Amazing work @sirselim. Your generous contributions in terms of this documentation is definitely going to save a lot of time for many including me! Thank you very much.

While installing readfish I got stuck when installing this *ont_pyguppy_client_lib*. Sorry if I overlooked something which you had already documented somewhere. How do I obtain the *ont_pyguppy_client_lib-4.0.15-cp37-cp37m-linux_aarch64.whl* file (for the `pip install Downloads/xavier_minit_build/ont_pyguppy_client_lib-4.0.15-cp37-cp37m-linux_aarch64.whl` command under the README)? I was looking through the pypi repositories for ont_pyguppy_client_lib but could not find any AARCH64 builds.

**Comment by sirselim** [comment]
Thanks for the kind words, it's my pleasure and I am very glad people are finding it useful.

Ah, I should have documented this better. I had to ask ONT nicely to compile an ARM version of `pyguppy_client` for me. It's frustrating and is on my list of things to request that they might like to include in their build chain (it took me about 9 months to do this for the ARM version of guppy but it's routinely built with the other versions now).

The other option is if you have signed the developer agreement, the source code is in there. You can then compile it yourself. I don't have access but @mikblack recently did this and has it running nicely on a Xavier NX.

The other caveat is that this library is inherently tied to each version of guppy from what I can tell. So the version I have is for a quite old version now (4.0.15). I imagine that if you're running the current latest guppy with minknow there will be a 4.3.4 version of `pyguppy_client`.

Sorry I can't be of more help, other than continuing to appeal to ONT to make more of this stuff accessible to the wider community.

**Comment by mikblack** [comment]
Hi @hasindu2008 - I ran into the same problem the other day when I was getting readfish set up on a Xavier NX. 
@sirselim is correct - I had to build an ARM version of `pyguppy_client` from source, which lives in a private ONT github repo (accessible once you've signed the ONT developer agreement). I'll be writing up some notes on the process over the next week or so.
