### ISSUE TITLE
A couple of background questions

### ISSUE THREAD

**Issue by ruy-jauregui** [sirselim/jetson_nanopore_sequencing#5]
Hello!
Thanks a lot for this excellent documentation, it inspired us to try a Jeston, install it and bring it up to speed.
We got a Jetson AGX Xavier, and followed your advice mostly without issues, until reaching testing time. The two general questions standing are:
Did you have any issue setting the time in Jetpack? The time is configured to be read automatically from the internet, but it's wrong. This throws some programs out of kilt. We haven't managed to fix this yet.

Then, we are having issues doing live base calling using minKNOW. minKNOW runs OK, as long as guppy is turned off. Did you manage to do live base calling? if so, how?

Cheers!

**Comment by sirselim** [comment]
Hi @ruy-jauregui.

No issues with system time on any of our Jetson devices (3x Xavier AGX and >10 Xavier NX), my guess is it might be something to do with your network?

In terms of live basecalling, yes it works beautifully on the Jetson devices. Have you ensured that you are running the correct version of Guppy to go alongside the version of MinKNOW that you have installed? For MinKNOW for **MinIT 21.05.8** this is Guppy **5.0.11**, see the below table for all packages and their version requirements for this latest build.

MinIT release **21.05.8** Components
package | version
-----------------------------------:|:--------------
minknow-core-minit-offline | 4.3.4
ont-bream4-minit | 6.2.5
ont-kingfisher-ui-minit | 4.3.20
ont-guppy-for-minit | 5.0.11
ont-configuration-customer-minit | 4.3.9
ont-system-identification-minit | 3.6.8
ont-minit-mooneye (Device Settings) | 1.4.19
ont-vbz-hdf-plugin | 1.0.0

I collate a table of these versions [here](https://github.com/sirselim/jetson_nanopore_sequencing#minknow--guppy-compatibility) and [here](https://hackmd.io/XbpQsODuRKe2yRj7OnDdQA#Guppy--MinKNOW-compatibility).
