### ISSUE TITLE
MinKNOW on TX2

### ISSUE THREAD

**Issue by hanfan1803** [sirselim/jetson_nanopore_sequencing#6]
Hi Miles

I am trying to test MinKNOW on a TX2. TX2 development kit was flashed with Jetsonpack 4.5.1 several days ago. I followed your instruction but when I start MinKNOW GUI I got a error messege: 

Unable to listen to button events.
Error: Can't initialize nvrm channel 
nvdc: Open: Operation not permitted
nvdc: failed to open '/dev/tegra_dc_ctrl'
...

The notes keep coming in the terminal. Due to the message, should I focus on nvrm channel, and how to give nvdc permission to open /dev/tegra_dc_ctrl file.

Best,
Han

**Comment by hanfan1803** [comment]
FYI
My identity.config file:

Build=V1
Class=MinIT
ProductCode=MIN-101B
Architecture=aarch64
Disk_technology=nvme
Gpu_type=Jetson
Memory=7Gi
Name=MinIT
No_of_cores=6
No_of_disks=12
No_of_gpus=1
Product_code=MIN-101B
Version=V1

It looks like jetson tx2 is recognized by ONT. 
When you look at all ONT product model numbers (https://assets.ctfassets.net/obrbum38fjyj/1LcrIVIUIuJu8WpaehR5FC/62f776140cc9dd6b1c08d197da63b58a/J0335_Safety_Doc_Smallprint_A4_Digi_AMEND_V8__002__-_Online_Rev002.pdf), the Jetson TX2 Development Kit is sort of between MinION M1B (Model number: Min-101B) and MinIT (Model number: MNT-001). 

As using MinIT repo, should I downgrade TX2 to Ubuntu 16 with Jetpack 3.3.3 (which contains Ubuntu 16 and CUDA 9.0)?

Thanks,
Han

**Comment by sirselim** [comment]
@hanfan1803 - sorry I somehow missed this issue! Did you get it solved?

**Comment by sirselim** [comment]
I'm going to close this issue for now as there has been no response.
